/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
    id("xyz.jpenilla.run-paper") version "2.2.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}
group = "me.dalynkaa"
version = "1.0.0-SNAPSHOT"
description = "Bridge between BedWars and BungeeCord"
var artifactId = "bedwars"

allprojects {
    apply(plugin = "java-library")
    apply(plugin = "xyz.jpenilla.run-paper")
    apply(plugin = "com.github.johnrengelman.shadow")
    apply(plugin = "xyz.jpenilla.run-velocity")

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
        maven("https://repo.dalynkaa.me/repository/maven-snapshots/")
        maven { url = uri("https://nexus.iridiumdevelopment.net/repository/maven-releases/") }
        maven { url = uri("https://repo.plasmoverse.com/releases") }
        maven { url = uri("https://repo.plasmoverse.com/snapshots") }
        maven { url = uri("https://maven.citizensnpcs.co/repo/") }
        maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
        maven { url = uri("https://oss.sonatype.org/content/groups/public/") }
        maven { url = uri("https://maven.enginehub.org/repo/") }
        maven { url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/") }
        maven { url = uri("https://repo.ranull.com/maven/external/") }
        maven { url = uri("https://repo.codemc.io/repository/maven-snapshots/") }
        maven { url = uri("https://repo.codemc.org/repository/maven-public/") }
        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }
        maven { url = uri("https://repo.kryptonmc.org/releases/") }
        maven { url = uri("https://mvn.lumine.io/repository/maven-public/") }
        maven { url = uri("https://jitpack.io/") }
        maven { url = uri("https://repo.inventivetalent.org/repository/public/") }
        maven { url = uri("https://repo.dmulloy2.net/repository/public/") }
    }
    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
    }
}
tasks {
    assemble {
        dependsOn(shadowJar)
    }

    shadowJar {
        archiveBaseName.set(rootProject.name)
        archiveClassifier.set("")
        dependsOn(":main:shadowJar")
        dependsOn(":lobby:shadowJar")
    }
    runServer {
        dependsOn(":main:runServer")
        dependsOn(":lobby:runServer")
        dependsOn(":proxy:runVelocity")
    }
}

dependencies {

}


