name: SPBedWars
version: '${project.version}'
main: me.dalynkaa.spbedwars.SPBedWars
api-version: 1.19
load: POSTWORLD
depend:
  - ProtocolLib
  - PlayerNPC
  - ItemsAdder
softdepend:
  - PlayerNPC
  - Citizens
  - PlaceholderAPI
  - Vault
  - WorldEdit
  - WorldGuard
commands:
  arena:
    description: this command use for create arenas
  game:
    description: this command use for manage games
  bedwars:
    description: this command use for manage plugin
    aliases:
      - bw
      - bwars