huds_refresh_interval_ticks: 20
huds_high_frequency_refresh_interval_ticks: 1
legacy_1_18_and_lower_textures: false
money:
  enabled: true
  offset: 91
  worlds:
    - world
    - world_nether
    - world_the_end
lang:
  hud_not_found: "&6Худ не найден!"
  wrong_usage: "&cОшибка написания команды."
  destination_set: "&aТочка прибытия установлена."
  destination_removed: "&7Точка прибытия убрана."
log:
  debug: true